apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: go-team-api
  name: go-team-api-service
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: go-team-api
  type: ClusterIP
status:
  loadBalancer: {}
