# Build Pipeline
# cbellee.go-team-ci

trigger:
  branches:
    include:
    - master
    - dev
    - stg
  paths:
    include:
    - api/*

pool:
  vmImage: 'ubuntu-latest'
variables:
  serviceConnection: 'Azure CXP FTA Internal Subscription CBELLEE (b2375b5f-8dab-4436-b87c-32bc7fdce5d0)'
  acrName: $(azureContainerRegistryName)
  version.Major: 0
  version.Minor: 1
  version.Patch: 0
  version.Revision: $[counter(variables['version.Patch'], 0)]
  imageVersion: "$(version.Major).$(version.Minor).$(version.Patch).$(Build.BuildId)"
  imageName: $(Build.Repository.Name)

steps:
- task: AzureCLI@2
  displayName: 'Push and Build Image in ACR'
  enabled: false
  inputs:
    azureSubscription: $(serviceConnection)
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az acr build --registry $(acrName) --image $(imageName):$(Build.SourceBranchName)-$(imageVersion) ./api
    
- task: Docker@2
  inputs:
    containerRegistry: 'belstarr.docker.io'
    repository: 'go-team'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    buildContext: './api'
    tags: '$(Build.SourceBranchName)-$(imageVersion)'